apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: instana-global
stringData:
  config.yaml: |-
      ---
      dhParams: |
        -----BEGIN DH PARAMETERS-----
        MIICCAKCAgEA+c91KqPF37XsbKbACDQG6FYDk2LnTOrJHknZCsNN9zDgdZlrawMI
        L43iaexeG+qybHrVcNo3XxDN9J66zg9ZeaYSgHQC7IbTxfO+quV/sVBaHHyL8jAX
        JrjjtjaLEd01dGuBvTFXT74v23ojW7hItns+QFGChSz0PTIvRee04o+oAfQN2+zV
        JNMzgcgDm8rowwAS3WERAT0Yfub2GZdFzrHvhinaRWMs2XfJiR/14IDymGwIVctc
        LdiVOp0es4A/S+/AieYTaJG6XqC0hJo/D7iman/oagSVPM+l5cn+kpHCLL0I6vlN
        OfeiQQgeIE0J6kKLGEhrI7dT/lWOmaDM5IBowRRQ54pwe/ZCaWuef8vTG3/drPZc
        V2nzIGp+j3fGTWQGtw43n+rf5/6mcoJjujMuyUWCsZrjlu3A7riX8V75iwysFhng
        mPJeKySxYKdJt20/L9QSd0zwFe5h2Q9jc+YC1ra/3Hm6ugTXBZQ7vHtxkzTnrbH+
        2RKbTp6m8ZZ/DJ2UU1PsrClNjC/8KCiUIhfTs+Co5xSP/ke50A6KERpA1jG+Gw9d
        CtX4hbCpUGULcrv+LbnskACDdlBVwoHFkG+xTTDDP+OB+GE9CWLE2HRREM1tTwjk
        /fGCYn4P/m3u4BcsEtqgYLoljya+WEAfsnqMLd7Sfm19wUJ9Dcq9PLMCAQI=
        -----END DH PARAMETERS-----
      downloadKey: "${downloadKey}"
      salesKey: "${salesKey}"
      tokenSecret: "${tokenSecret}"
      adminAPIPassword: "${datastorePassword}"
      serviceAPIPassword: "${datastorePassword}"
      repositoryURL: "https://maven.instana.io/artifactory/shared/"
      repositoryUser: "_"
      repositoryPassword: "${downloadKey}"
      datastoreConfigs:
        postgresConfigs:
          - user: postgres
            password: "${datastorePassword}"
            adminUser: postgres
            adminPassword: "${datastorePassword}"
            databases:
              - butlerdb
              - tenantdb
              - sales
              - instanactl      
        kafkaConfig:
          adminUser: "instana-kafka-user"
          adminPassword: "${datastorePassword}"
          consumerUser: "instana-kafka-user"
          consumerPassword: "${datastorePassword}"
          producerUser: "instana-kafka-user"
          producerPassword: "${datastorePassword}"

