apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: beeinstana-operator
subjects:
- kind: ServiceAccount
  name: beeinstana-operator
  namespace: beeinstana-operator
roleRef:
  kind: ClusterRole
  name: beeinstana-operator
  apiGroup: rbac.authorization.k8s.io
