---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elastic
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: elastic-system
  chart:
    spec:
      chart: eck-operator
      version: "v2.6.1"
      sourceRef:
        kind: HelmRepository
        name: elastic
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    installCRDs: true
    nodeSelector:
      "workloads.instana.io/operator": "true"
