---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-ebs-csi-driver
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kube-system
  chart:
    spec:
      chart: aws-ebs-csi-driver
      version: "2.18.0"
      sourceRef:
        kind: HelmRepository
        name: aws-ebs-csi-driver
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    controller: 
      serviceAccount:
        annotations:
          "eks.amazonaws.com/role-arn": "arn:aws:iam::${cloudProjectId}:role/in-${regionDeploymentName:=unknown}-aws-addons"
    node: 
      serviceAccount:
        annotations:
          "eks.amazonaws.com/role-arn": "arn:aws:iam::${cloudProjectId}:role/in-${regionDeploymentName:=unknown}-aws-addons"
