---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clickhouse
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: ch-system # Shorten Zookeeper here to work around `must be no more than 63 characters`.
  chart:
    spec:
      chart: altinity-clickhouse-operator
      version: "v0.20.1"
      sourceRef:
        kind: HelmRepository
        name: clickhouse
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    installCRDs: true
    nodeSelector:
      "workloads.instana.io/operator": "true"
    operator:
      env:
        - name: WATCH_NAMESPACE
          value: datastores
