---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: kyverno-operator
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/kyverno
  targetNamespace: flux-system
  prune: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno-system-kyverno
      namespace: kyverno-system      
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
