---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: region
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./regions/lilac/installation
  prune: true
  dependsOn:
    - name: infrastructure
    - name: aws-installation
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-key
