apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patchesStrategicMerge:
  - |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: kustomize-controller
      namespace: flux-system
      annotations:
        "eks.amazonaws.com/role-arn": "arn:aws:iam::410797082306:role/in-lilac-pods"
  - |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: kustomize-controller
      namespace: flux-system
    spec:
      template:
        spec:
          containers:
            - name: manager
              env:
                - name: "AWS_SDK_LOAD_CONFIG"
                  value: "1"