---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-pricing
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  gcp.json:  | 
    {{ .Values.opencost.pricing | toJson }}
