apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    "prometheus.io/scrape": "true"
    "prometheus.io/scheme": "http"
    "prometheus.io/path": "/metrics"
    "prometheus.io/port": "9003"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9003
      targetPort: opencost
      protocol: TCP
      name: opencost
  selector:
    {{- include "chart.selectorLabels" . | nindent 4 }}
