---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: aws-efs-csi-driver
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/aws-efs-csi-driver
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  postBuild:
    substituteFrom:
      - name: cloud-provider-constants
        kind: ConfigMap
