---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: telepresence
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: telepresence-system
  releaseName: "traffic-manager"
  chart:
    spec:
      chart: telepresence
      version: "2.12.1"
      sourceRef:
        kind: HelmRepository
        name: telepresence
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: false
  values:
    nodeSelector:
      "workloads.instana.io/operator": "true"
