---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: region-units
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./regions/heliconia/units
  prune: true
  targetNamespace: instana-units
  dependsOn:
    - name: region-region
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-key
