---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: region-base
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./regions/base/installation
  prune: true
  wait: true
  dependsOn:
    - name: region-config
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-key
