---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: instana-kafka-user
  labels:
    strimzi.io/cluster: kafka
spec:
  authentication:
    type: scram-sha-512
  authorization:
    type: simple
    acls:
      - resource:
          type: topic
          name: '*'
          patternType: literal
        operations:
          - All
        host: "*"