---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kyverno-system
  chart:
    spec:
      chart: kyverno
      version: "2.7.0-rc.2"
      sourceRef:
        kind: HelmRepository
        name: kyverno
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    installCRDs: true
    replicaCount: 3
    nodeSelector:
      "workloads.instana.io/operator": "true"
