---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: prometheus
  chart:
    spec:
      chart: prometheus
      version: "19.3.3"
      sourceRef:
        kind: HelmRepository
        name: prometheus
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    pushgateway:
      enabled: false
    alertmanager:
      enabled: false
    prometheus-node-exporter:
      enabled: false
    server:
      retention: "72h"
      nodeSelector:
        "workloads.instana.io/operator": "true"