---
apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-acceptor
spec:
  type: LoadBalancer
  ports:
    - name: http-service
      port: 443
      protocol: TCP
      targetPort: http-service
  selector:
    app.kubernetes.io/name: instana
    app.kubernetes.io/component: acceptor
    instana.io/group: service