---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: region-region
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./regions/lilac/region
  targetNamespace: instana-region
  prune: true
  dependsOn:
    - name: region-config
    - name: region-base
    - name: region-base-regional
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-key
  postBuild:
    substituteFrom:
      - name: region-config
        kind: ConfigMap
      - name: region-secrets
        kind: Secret