---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: zookeeper
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: zk-system # Shorten Zookeeper here to work around `must be no more than 63 characters`.
  chart:
    spec:
      chart: zookeeper-operator
      version: "0.2.14"
      sourceRef:
        kind: HelmRepository
        name: zookeeper
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    installCRDs: true
    fullnameOverride: "zookeeper-operator"
    nodeSelector:
      "workloads.instana.io/operator": "true"

