apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml

patchesStrategicMerge:
  - |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: kustomize-controller
      namespace: flux-system
      annotations:
        iam.gke.io/gcp-service-account: in-heliconia-pods@instana-non-production.iam.gserviceaccount.com 