---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cassandra
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: cassandra-system
  chart:
    spec:
      chart: cass-operator
      version: "v0.37.1"
      sourceRef:
        kind: HelmRepository
        name: cassandra
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    installCRDs: true
    fullnameOverride: "cassandra-operator"
    nodeSelector:
      "workloads.instana.io/operator": "true"
    global:
      clusterScoped: true
