---
apiVersion: zookeeper.pravega.io/v1beta1
kind: ZookeeperCluster
metadata:
  name: zookeeper-application
spec:
  replicas: ${zookeeperApplicationCount:=3}
  labels:
    "app.kubernetes.io/name": zookeeper
    "instana.io/single-tenant": "true"
  storageType: persistence
  persistence:
    reclaimPolicy: Delete
    spec:
      storageClassName: "instana-standard"
      resources:
        requests:
          storage: ${zookeeperApplicationVolumeSize:=128}Gi
  pod:
    resources:
      requests:
        cpu: ${zookeeperApplicationCpu:=14}
        memory: ${zookeeperApplicationMemory:=24}Gi
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: "workloads.instana.io/zookeeper"
                operator: In
                values:
                  - "true"
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - key: "instana.io/single-tenant"
                  operator: In
                  values:
                    - "true"
            topologyKey: kubernetes.io/hostname 
