---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: cert-manager
  chart:
    spec:
      chart: cert-manager
      version: "v1.11.0"
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    installCRDs: true
    global:
      leaderElection:
        namespace: cert-manager
    nodeSelector:
      "workloads.instana.io/operator": "true"
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-service-account
