apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: instana
    app.kubernetes.io/version: 241-0
  name: instana-operator
  namespace: instana-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      app.kubernetes.io/name: instana
  template:
    metadata:
      labels:
        app.kubernetes.io/component: operator
        app.kubernetes.io/name: instana
        app.kubernetes.io/version: 241-0
    spec:
      containers:
        - args:
            - /app/instana-operator
          env:
            - name: INSTANA_TESTMODE
              value: "true"
            - name: SSL_CERT_DIR
              value: "/etc/pki/tls/certs/:/opt/instana/certs"
            - name: INSTANA_DISABLE_DB_VERSION_CHECKS
              value: "true"
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: delivery.instana.io/int-docker-private-virtual/infrastructure/instana-operator:245-0
          imagePullPolicy: IfNotPresent
          name: instana-operator
          ports:
            - containerPort: 8081
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: http
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          volumeMounts:
            - mountPath: /tmp
              name: tmpdir
            - mountPath: /opt/instana/certs
              name: custom-certs
      enableServiceLinks: false
      serviceAccountName: instana-operator
      terminationGracePeriodSeconds: 300
      volumes:
        - emptyDir: {}
          name: tmpdir
        - name: custom-certs
          configMap:
            name: custom-certs
            optional: true
