---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: regional-datastores
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./regions/base-regional/datastores
  targetNamespace: datastores
  prune: true
  dependsOn:
    - name: base-namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-key
  postBuild:
    substituteFrom:
      - name: region-config
        kind: ConfigMap
      - name: region-secrets
        kind: Secret
  # If migrations fail in Clickhouse its really difficult to sort out.
  # As a workaround, ensure that Clickhouse clusters and their supporting
  # Zookeeper clusters are healthy before proceeding. 
  healthChecks:
    - apiVersion: v1
      kind: Service
      name: clickhouse-application
      namespace: datastores
    - apiVersion: v1
      kind: Service
      name: clickhouse-logs
      namespace: datastores
    - apiVersion: v1
      kind: Service
      name: zookeeper-application-headless
      namespace: datastores
    - apiVersion: v1
      kind: Service
      name: zookeeper-logs-headless
      namespace: datastores
