---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: opencost
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: opencost
  chart:
    spec:
      chart: "./infrastructure/opencost/chart"
      version: "0.1.5"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    nodeSelector:
      "workloads.instana.io/operator": "true"
  valuesFrom:
    - kind: Secret
      name: opencost-config