---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: haproxy
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: postgres-proxy
  chart:
    spec:
      chart: haproxy
      version: "1.18.0"
      sourceRef:
        kind: HelmRepository
        name: haproxy
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    containerPorts:
      http: 5432
    nodeSelector:
      "workloads.instana.io/operator": "true"
    config: |
      global
        log stdout format raw local0
        maxconn 1024
      
      defaults
        log global
        timeout client 60s
        timeout connect 60s
        timeout server 60s
      
      frontend fe_main
        bind :5432
        default_backend be_main
      
      backend be_main
        server pg_back in-pg.${regionDeploymentName}-internal.${regionDomainName}:5432 check
