---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: instana-issuer
spec:
  acme:
    email: ops+acme.staging@instana.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: instana-issuer-account-key
    solvers:
      - dns01:
          cloudDNS:
            project: "${cloudProjectName}"
            hostedZoneName: "${acmeZoneName}"
        selector:
          matchLabels:
            "instana.io/certificate-source": "letsencrypt"
            "instana.io/cloud-provider": "gcp"
      - dns01:
          route53:
            region: "${cloudProjectRegion}"
            hostedZoneID: "${acmeZoneName}"
        selector:
          matchLabels:
            "instana.io/certificate-source": "letsencrypt"
            "instana.io/cloud-provider": "aws"