---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: base-namespaces
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./regions/base/namespaces
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-key
  postBuild:
    substituteFrom:
      - name: region-config
        kind: ConfigMap
      - name: region-secrets
        kind: Secret
