---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: clusterroles
  namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: "./infrastructure/clusterroles/chart"
      version: "0.2.0"
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    cloudProviderName: "${cloudProvider}"