---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: clone-instana-registry-secret
spec:
  generateExistingOnPolicyUpdate: true
  rules:
  - name: clone-secret-into-new-namespace
    match:
      resources:
        kinds:
        - Namespace
    generate:
      kind: Secret
      name: instana-registry 
      namespace: "{{request.object.metadata.name}}"
      synchronize : true
      clone:
        name: instana-registry
        namespace: flux-system
        