---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: policies
resources:
  - cass-operator-on-operator-workload-nodes.yaml
  - clone-instana-registry-secret.yaml
  - images-from-instana-registry.yaml
  - helm-charts-from-instana-repository.yaml
