---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: kube-system
  chart:
    spec:
      chart: aws-load-balancer-controller
      version: "1.4.8"
      sourceRef:
        kind: HelmRepository
        name: aws-load-balancer-controller
      interval: 1m
  upgrade:
    remediation:
      remediateLastFailure: true
  test:
    enable: true
  values:
    clusterName: "in-${regionDeploymentName:=unknown}"
    serviceAccount:
      annotations:
        "eks.amazonaws.com/role-arn": "arn:aws:iam::${cloudProjectId}:role/in-${regionDeploymentName:=unknown}-aws-addons"
