---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: aws-load-balancer-controller
  namespace: flux-system
spec:
  interval: 5m0s
  url: "https://aws.github.io/eks-charts"