{{- if eq .Values.cloudProviderName "aws" }}
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: instana-archival
  labels:
    {{- include "chart.labels" . | nindent 4 }}
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: st1
  encrypted: "true"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: instana-standard
  labels:
    {{- include "chart.labels" . | nindent 4 }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
  encrypted: "true"
{{- end }}
