{{- if eq .Values.cloudProviderName "gcp" }}
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: instana-archival
  labels:
    {{- include "chart.labels" . | nindent 4 }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  fsType: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: instana-standard
  labels:
    {{- include "chart.labels" . | nindent 4 }}
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-balanced
  csi.storage.k8s.io/fstype: ext4
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
{{- end }}
