---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: beeinstana
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/beeinstana
  prune: true
  dependsOn:
    - name: cert-manager
    - name: kustomize-operator-namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
    - target:
        kind: ServiceAccount
        name: beeinstana-operator
      patch: |
        - op: add
          path: /imagePullSecrets
          value:
            - name: instana-registry
    - target:
        kind: Deployment
        name: beeinstana-operator
      patch: |
        - op: replace
          path: /spec/template/spec/containers/0/env
          value:
            - name: OPERATOR_NAMESPACE
              value: "datastores"
        - op: add
          path: /spec/template/spec/containers/0/nodeSelector
          value:
            "workloads.instana.io/operator": "true"