---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: instana
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/instana
  prune: true
  dependsOn:
    - name: cert-manager
    - name: kustomize-operator-namespaces
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  patches:
    - target:
        kind: ServiceAccount
        name: instana-operator-webhook
        namespace: instana-operator
      patch: |
        - op: add
          path: /imagePullSecrets
          value:
            - name: instana-registry
    - target:
        kind: ServiceAccount
        name: instana-operator
        namespace: instana-operator
      patch: |
        - op: add
          path: /imagePullSecrets
          value:
            - name: instana-registry
    - target:
        kind: Deployment
        name: instana-operator-webhook
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/nodeSelector
          value:
            "workloads.instana.io/operator": "true"
    - target:
        kind: Deployment
        name: instana-operator
      patch: |
        - op: add
          path: /spec/template/spec/containers/0/nodeSelector
          value:
            "workloads.instana.io/operator": "true"
