---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: infrastructure-install
resources:
  - kustomize-operator-namespaces.yaml
  - elastic.yaml
  - cert-manager.yaml
  - zookeeper.yaml
  - clickhouse.yaml
  - kafka.yaml
  - cassandra.yaml
  - instana.yaml
  - beeinstana.yaml
  - storageclasses.yaml
  - prometheus.yaml
  - opencost.yaml
  - instana-agent.yaml
  - haproxy.yaml
  - telepresence.yaml