---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: opencost
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/opencost
  dependsOn:
    - name: prometheus
    - name: kustomize-operator-namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
