---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: telepresence
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/telepresence
  targetNamespace: flux-system
  dependsOn:
    - name: kyverno-policies
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
