---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: crowdstrike-falcon
  namespace: flux-system
spec:
  interval: 5m0s
  url: "https://crowdstrike.github.io/falcon-helm"